export interface Emoji {
  emoji: string;
  description: string;
  category: string;
  aliases: string[];
  tags: string[];
}

export const EMOJI_DATA: Emoji[] = [
  // Smileys & Emotion
  { emoji: '😀', description: 'grinning face', category: 'Smileys & Emotion', aliases: ['grinning'], tags: ['smile', 'happy'] },
  { emoji: '😃', description: 'grinning face with big eyes', category: 'Smileys & Emotion', aliases: ['smiley'], tags: ['happy', 'joy', 'haha'] },
  { emoji: '😄', description: 'grinning face with smiling eyes', category: 'Smileys & Emotion', aliases: ['smile'], tags: ['happy', 'joy', 'laugh', 'pleased'] },
  { emoji: '😁', description: 'beaming face with smiling eyes', category: 'Smileys & Emotion', aliases: ['grin'], tags: [] },
  { emoji: '😆', description: 'grinning squinting face', category: 'Smileys & Emotion', aliases: ['laughing', 'satisfied'], tags: ['happy', 'haha'] },
  { emoji: '😅', description: 'grinning face with sweat', category: 'Smileys & Emotion', aliases: ['sweat_smile'], tags: ['hot'] },
  { emoji: '🤣', description: 'rolling on the floor laughing', category: 'Smileys & Emotion', aliases: ['rofl'], tags: ['lol', 'laughing'] },
  { emoji: '😂', description: 'face with tears of joy', category: 'Smileys & Emotion', aliases: ['joy'], tags: ['tears'] },
  { emoji: '🙂', description: 'slightly smiling face', category: 'Smileys & Emotion', aliases: ['slightly_smiling_face'], tags: [] },
  { emoji: '🙃', description: 'upside-down face', category: 'Smileys & Emotion', aliases: ['upside_down_face'], tags: ['sarcasm'] },
  { emoji: '😉', description: 'winking face', category: 'Smileys & Emotion', aliases: ['wink'], tags: ['flirt'] },
  { emoji: '😊', description: 'smiling face with smiling eyes', category: 'Smileys & Emotion', aliases: ['blush'], tags: ['proud'] },
  { emoji: '😇', description: 'smiling face with halo', category: 'Smileys & Emotion', aliases: ['innocent'], tags: ['angel'] },
  { emoji: '🥰', description: 'smiling face with hearts', category: 'Smileys & Emotion', aliases: ['smiling_face_with_three_hearts'], tags: ['love'] },
  { emoji: '😍', description: 'smiling face with heart-eyes', category: 'Smileys & Emotion', aliases: ['heart_eyes'], tags: ['love', 'crush'] },
  { emoji: '🤩', description: 'star-struck', category: 'Smileys & Emotion', aliases: ['star_struck'], tags: ['eyes'] },
  { emoji: '😘', description: 'face blowing a kiss', category: 'Smileys & Emotion', aliases: ['kissing_heart'], tags: ['flirt'] },
  { emoji: '😗', description: 'kissing face', category: 'Smileys & Emotion', aliases: ['kissing'], tags: [] },
  { emoji: '😋', description: 'face savoring food', category: 'Smileys & Emotion', aliases: ['yum'], tags: ['tongue', 'lick'] },
  { emoji: '😛', description: 'face with tongue', category: 'Smileys & Emotion', aliases: ['stuck_out_tongue'], tags: [] },
  { emoji: '😜', description: 'winking face with tongue', category: 'Smileys & Emotion', aliases: ['stuck_out_tongue_winking_eye'], tags: ['joke', 'silly'] },
  { emoji: '🤪', description: 'zany face', category: 'Smileys & Emotion', aliases: ['zany_face'], tags: ['goofy', 'silly'] },
  { emoji: '🤨', description: 'face with raised eyebrow', category: 'Smileys & Emotion', aliases: ['face_with_raised_eyebrow'], tags: ['suspicious'] },
  { emoji: '🧐', description: 'face with monocle', category: 'Smileys & Emotion', aliases: ['face_with_monocle'], tags: ['stuffy'] },
  { emoji: '🤓', description: 'nerd face', category: 'Smileys & Emotion', aliases: ['nerd_face'], tags: ['geek', 'glasses'] },
  { emoji: '😎', description: 'smiling face with sunglasses', category: 'Smileys & Emotion', aliases: ['sunglasses'], tags: ['cool'] },
  { emoji: '🥳', description: 'partying face', category: 'Smileys & Emotion', aliases: ['partying_face'], tags: ['celebration', 'party'] },
  { emoji: '😏', description: 'smirking face', category: 'Smileys & Emotion', aliases: ['smirk'], tags: ['smug'] },
  { emoji: '😒', description: 'unamused face', category: 'Smileys & Emotion', aliases: ['unamused'], tags: ['bored', 'sad'] },
  { emoji: '😞', description: 'disappointed face', category: 'Smileys & Emotion', aliases: ['disappointed'], tags: ['sad'] },
  { emoji: '😔', description: 'pensive face', category: 'Smileys & Emotion', aliases: ['pensive'], tags: [] },
  { emoji: '😟', description: 'worried face', category: 'Smileys & Emotion', aliases: ['worried'], tags: ['nervous'] },
  { emoji: '😕', description: 'confused face', category: 'Smileys & Emotion', aliases: ['confused'], tags: [] },
  { emoji: '🙁', description: 'slightly frowning face', category: 'Smileys & Emotion', aliases: ['slightly_frowning_face'], tags: [] },
  { emoji: '☹️', description: 'frowning face', category: 'Smileys & Emotion', aliases: ['frowning_face'], tags: [] },
  { emoji: '😮', description: 'face with open mouth', category: 'Smileys & Emotion', aliases: ['open_mouth'], tags: ['surprise', 'shock'] },
  { emoji: '😯', description: 'hushed face', category: 'Smileys & Emotion', aliases: ['hushed'], tags: ['silent', 'quiet'] },
  { emoji: '😲', description: 'astonished face', category: 'Smileys & Emotion', aliases: ['astonished'], tags: ['shocked'] },
  { emoji: '😳', description: 'flushed face', category: 'Smileys & Emotion', aliases: ['flushed'], tags: ['blushing'] },
  { emoji: '🥺', description: 'pleading face', category: 'Smileys & Emotion', aliases: ['pleading_face'], tags: ['puppy', 'eyes'] },
  { emoji: '😦', description: 'frowning face with open mouth', category: 'Smileys & Emotion', aliases: ['frowning'], tags: [] },
  { emoji: '😧', description: 'anguished face', category: 'Smileys & Emotion', aliases: ['anguished'], tags: ['pain'] },
  { emoji: '😨', description: 'fearful face', category: 'Smileys & Emotion', aliases: ['fearful'], tags: ['scared'] },
  { emoji: '😰', description: 'anxious face with sweat', category: 'Smileys & Emotion', aliases: ['cold_sweat'], tags: ['nervous'] },
  { emoji: '😥', description: 'sad but relieved face', category: 'Smileys & Emotion', aliases: ['disappointed_relieved'], tags: ['phew', 'sweat'] },
  { emoji: '😢', description: 'crying face', category: 'Smileys & Emotion', aliases: ['cry'], tags: ['sad', 'tear'] },
  { emoji: '😭', description: 'loudly crying face', category: 'Smileys & Emotion', aliases: ['sob'], tags: ['sad', 'cry', 'tears'] },
  { emoji: '😱', description: 'face screaming in fear', category: 'Smileys & Emotion', aliases: ['scream'], tags: ['horror', 'shocked'] },
  { emoji: '😖', description: 'confounded face', category: 'Smileys & Emotion', aliases: ['confounded'], tags: ['confused', 'sick'] },
  { emoji: '😣', description: 'persevering face', category: 'Smileys & Emotion', aliases: ['persevere'], tags: ['struggling'] },
  { emoji: '😞', description: 'disappointed face', category: 'Smileys & Emotion', aliases: ['disappointed'], tags: ['sad'] },
  { emoji: '😓', description: 'downcast face with sweat', category: 'Smileys & Emotion', aliases: ['sweat'], tags: [] },
  { emoji: '😩', description: 'weary face', category: 'Smileys & Emotion', aliases: ['weary'], tags: ['tired'] },
  { emoji: '😫', description: 'tired face', category: 'Smileys & Emotion', aliases: ['tired_face'], tags: ['upset', 'whine'] },
  { emoji: '🥱', description: 'yawning face', category: 'Smileys & Emotion', aliases: ['yawning_face'], tags: ['tired'] },
  { emoji: '😤', description: 'face with steam from nose', category: 'Smileys & Emotion', aliases: ['triumph'], tags: ['smug'] },
  { emoji: '😡', description: 'pouting face', category: 'Smileys & Emotion', aliases: ['pout'], tags: ['angry'] },
  { emoji: '😠', description: 'angry face', category: 'Smileys & Emotion', aliases: ['angry'], tags: ['mad'] },
  { emoji: '🤬', description: 'face with symbols on mouth', category: 'Smileys & Emotion', aliases: ['face_with_symbols_on_mouth'], tags: ['swearing'] },
  { emoji: '😈', description: 'smiling face with horns', category: 'Smileys & Emotion', aliases: ['smiling_imp'], tags: ['devil', 'evil'] },
  { emoji: '👿', description: 'angry face with horns', category: 'Smileys & Emotion', aliases: ['imp'], tags: ['devil', 'evil'] },
  { emoji: '💀', description: 'skull', category: 'Smileys & Emotion', aliases: ['skull'], tags: ['dead', 'danger'] },
  { emoji: '💩', description: 'pile of poo', category: 'Smileys & Emotion', aliases: ['hankey', 'poop', 'shit'], tags: ['crap'] },
  { emoji: '🤡', description: 'clown face', category: 'Smileys & Emotion', aliases: ['clown_face'], tags: [] },
  { emoji: '👹', description: 'ogre', category: 'Smileys & Emotion', aliases: ['japanese_ogre'], tags: ['monster'] },
  { emoji: '👺', description: 'goblin', category: 'Smileys & Emotion', aliases: ['japanese_goblin'], tags: ['monster'] },
  { emoji: '👻', description: 'ghost', category: 'Smileys & Emotion', aliases: ['ghost'], tags: ['halloween'] },
  { emoji: '👽', description: 'alien', category: 'Smileys & Emotion', aliases: ['alien'], tags: ['ufo'] },
  { emoji: '👾', description: 'alien monster', category: 'Smileys & Emotion', aliases: ['space_invader'], tags: ['game', 'retro'] },
  { emoji: '🤖', description: 'robot', category: 'Smileys & Emotion', aliases: ['robot'], tags: ['bot'] },
  { emoji: '❤️', description: 'red heart', category: 'Smileys & Emotion', aliases: ['heart'], tags: ['love'] },
  { emoji: '🧡', description: 'orange heart', category: 'Smileys & Emotion', aliases: ['orange_heart'], tags: [] },
  { emoji: '💛', description: 'yellow heart', category: 'Smileys & Emotion', aliases: ['yellow_heart'], tags: [] },
  { emoji: '💚', description: 'green heart', category: 'Smileys & Emotion', aliases: ['green_heart'], tags: [] },
  { emoji: '💙', description: 'blue heart', category: 'Smileys & Emotion', aliases: ['blue_heart'], tags: [] },
  { emoji: '💜', description: 'purple heart', category: 'Smileys & Emotion', aliases: ['purple_heart'], tags: [] },
  { emoji: '🖤', description: 'black heart', category: 'Smileys & Emotion', aliases: ['black_heart'], tags: [] },
  { emoji: '💔', description: 'broken heart', category: 'Smileys & Emotion', aliases: ['broken_heart'], tags: [] },
  { emoji: '❣️', description: 'heart exclamation', category: 'Smileys & Emotion', aliases: ['heavy_heart_exclamation'], tags: [] },
  { emoji: '💕', description: 'two hearts', category: 'Smileys & Emotion', aliases: ['two_hearts'], tags: ['love'] },
  { emoji: '💞', description: 'revolving hearts', category: 'Smileys & Emotion', aliases: ['revolving_hearts'], tags: [] },
  { emoji: '💓', description: 'beating heart', category: 'Smileys & Emotion', aliases: ['heartbeat'], tags: [] },
  { emoji: '💗', description: 'growing heart', category: 'Smileys & Emotion', aliases: ['heartpulse'], tags: [] },
  { emoji: '💖', description: 'sparkling heart', category: 'Smileys & Emotion', aliases: ['sparkling_heart'], tags: [] },
  { emoji: '💘', description: 'heart with arrow', category: 'Smileys & Emotion', aliases: ['cupid'], tags: ['love'] },
  { emoji: '💝', description: 'heart with ribbon', category: 'Smileys & Emotion', aliases: ['gift_heart'], tags: ['chocolates'] },
  { emoji: '💟', description: 'heart decoration', category: 'Smileys & Emotion', aliases: ['heart_decoration'], tags: [] },
  { emoji: '💯', description: 'hundred points', category: 'Symbols', aliases: ['100'], tags: ['score', 'perfect'] },
  { emoji: '💥', description: 'collision', category: 'Smileys & Emotion', aliases: ['boom', 'collision'], tags: ['explode'] },
  { emoji: '💫', description: 'dizzy', category: 'Smileys & Emotion', aliases: ['dizzy'], tags: ['star'] },
  { emoji: '💦', description: 'sweat droplets', category: 'Smileys & Emotion', aliases: ['sweat_drops'], tags: ['water'] },
  { emoji: '💨', description: 'dashing away', category: 'Smileys & Emotion', aliases: ['dash'], tags: ['wind', 'blow'] },
  { emoji: '👋', description: 'waving hand', category: 'People & Body', aliases: ['wave'], tags: ['goodbye'] },
  { emoji: '👌', description: 'OK hand', category: 'People & Body', aliases: ['ok_hand'], tags: [] },
  { emoji: '✌️', description: 'victory hand', category: 'People & Body', aliases: ['v'], tags: ['peace'] },
  { emoji: '🤞', description: 'crossed fingers', category: 'People & Body', aliases: ['crossed_fingers'], tags: ['luck'] },
  { emoji: '🤟', description: 'love-you gesture', category: 'People & Body', aliases: ['love_you_gesture'], tags: [] },
  { emoji: '🤘', description: 'sign of the horns', category: 'People & Body', aliases: ['the_horns', 'sign_of_the_horns'], tags: ['rock_on'] },
  { emoji: '🤙', description: 'call me hand', category: 'People & Body', aliases: ['call_me_hand'], tags: [] },
  { emoji: '👈', description: 'backhand index pointing left', category: 'People & Body', aliases: ['point_left'], tags: [] },
  { emoji: '👉', description: 'backhand index pointing right', category: 'People & Body', aliases: ['point_right'], tags: [] },
  { emoji: '👆', description: 'backhand index pointing up', category: 'People & Body', aliases: ['point_up_2'], tags: [] },
  { emoji: '🖕', description: 'middle finger', category: 'People & Body', aliases: ['middle_finger', 'fu'], tags: [] },
  { emoji: '👇', description: 'backhand index pointing down', category: 'People & Body', aliases: ['point_down'], tags: [] },
  { emoji: '👍', description: 'thumbs up', category: 'People & Body', aliases: ['+1', 'thumbsup'], tags: ['approve', 'ok'] },
  { emoji: '👎', description: 'thumbs down', category: 'People & Body', aliases: ['-1', 'thumbsdown'], tags: ['disapprove', 'bury'] },
  { emoji: '✊', description: 'raised fist', category: 'People & Body', aliases: ['fist'], tags: ['power'] },
  { emoji: '👊', description: 'oncoming fist', category: 'People & Body', aliases: ['facepunch', 'punch'], tags: ['attack'] },
  { emoji: '👏', description: 'clapping hands', category: 'People & Body', aliases: ['clap'], tags: ['praise', 'applause'] },
  { emoji: '🙌', description: 'raising hands', category: 'People & Body', aliases: ['raised_hands'], tags: ['hooray'] },
  { emoji: '🙏', description: 'folded hands', category: 'People & Body', aliases: ['pray'], tags: ['please', 'thank_you'] },
  { emoji: '💪', description: 'flexed biceps', category: 'People & Body', aliases: ['muscle'], tags: ['strong', 'biceps'] },
  { emoji: '🧠', description: 'brain', category: 'People & Body', aliases: ['brain'], tags: ['intelligent'] },
  { emoji: '👀', description: 'eyes', category: 'People & Body', aliases: ['eyes'], tags: ['look', 'see'] },
  { emoji: '🗣️', description: 'speaking head', category: 'People & Body', aliases: ['speaking_head'], tags: [] },
  { emoji: '👤', description: 'bust in silhouette', category: 'People & Body', aliases: ['bust_in_silhouette'], tags: ['user'] },
  { emoji: '👥', description: 'busts in silhouette', category: 'People & Body', aliases: ['busts_in_silhouette'], tags: ['users', 'group', 'team'] },
  // Animals & Nature
  { emoji: '🐶', description: 'dog face', category: 'Animals & Nature', aliases: ['dog'], tags: ['pet'] },
  { emoji: '🐱', description: 'cat face', category: 'Animals & Nature', aliases: ['cat'], tags: ['pet'] },
  { emoji: '🐭', description: 'mouse face', category: 'Animals & Nature', aliases: ['mouse'], tags: [] },
  { emoji: '🐹', description: 'hamster face', category: 'Animals & Nature', aliases: ['hamster'], tags: ['pet'] },
  { emoji: '🐰', description: 'rabbit face', category: 'Animals & Nature', aliases: ['rabbit'], tags: ['bunny'] },
  { emoji: '🦊', description: 'fox face', category: 'Animals & Nature', aliases: ['fox_face'], tags: [] },
  { emoji: '🐻', description: 'bear face', category: 'Animals & Nature', aliases: ['bear'], tags: [] },
  { emoji: '🐼', description: 'panda face', category: 'Animals & Nature', aliases: ['panda_face'], tags: [] },
  { emoji: '🐨', description: 'koala', category: 'Animals & Nature', aliases: ['koala'], tags: [] },
  { emoji: '🐯', description: 'tiger face', category: 'Animals & Nature', aliases: ['tiger'], tags: [] },
  { emoji: '🦁', description: 'lion face', category: 'Animals & Nature', aliases: ['lion'], tags: [] },
  { emoji: '🐮', description: 'cow face', category: 'Animals & Nature', aliases: ['cow'], tags: [] },
  { emoji: '🐷', description: 'pig face', category: 'Animals & Nature', aliases: ['pig'], tags: [] },
  { emoji: '🐸', description: 'frog face', category: 'Animals & Nature', aliases: ['frog'], tags: [] },
  { emoji: '🐵', description: 'monkey face', category: 'Animals & Nature', aliases: ['monkey_face'], tags: [] },
  { emoji: '🦄', description: 'unicorn face', category: 'Animals & Nature', aliases: ['unicorn_face'], tags: [] },
  { emoji: '🐧', description: 'penguin', category: 'Animals & Nature', aliases: ['penguin'], tags: [] },
  { emoji: '🌍', description: 'globe showing Europe-Africa', category: 'Travel & Places', aliases: ['earth_africa'], tags: ['globe', 'world', 'international'] },
  { emoji: '🌎', description: 'globe showing Americas', category: 'Travel & Places', aliases: ['earth_americas'], tags: ['globe', 'world', 'international'] },
  { emoji: '🌏', description: 'globe showing Asia-Australia', category: 'Travel & Places', aliases: ['earth_asia'], tags: ['globe', 'world', 'international'] },
  { emoji: '🌱', description: 'seedling', category: 'Animals & Nature', aliases: ['seedling'], tags: ['plant', 'growth'] },
  { emoji: '🔥', description: 'fire', category: 'Travel & Places', aliases: ['fire'], tags: ['hot', 'burn'] },
  { emoji: '✨', description: 'sparkles', category: 'Activities', aliases: ['sparkles'], tags: ['stars', 'shine', 'shiny', 'magic'] },
  { emoji: '⭐', description: 'star', category: 'Travel & Places', aliases: ['star'], tags: ['night'] },
  { emoji: '⚡️', description: 'high voltage', category: 'Travel & Places', aliases: ['zap'], tags: ['lightning', 'thunder'] },
  { emoji: '💧', description: 'droplet', category: 'Objects', aliases: ['droplet'], tags: ['water', 'drip'] },
  // Food & Drink
  { emoji: '🍔', description: 'hamburger', category: 'Food & Drink', aliases: ['hamburger'], tags: ['burger'] },
  { emoji: '🍕', description: 'pizza', category: 'Food & Drink', aliases: ['pizza'], tags: [] },
  { emoji: '🥑', description: 'avocado', category: 'Food & Drink', aliases: ['avocado'], tags: [] },
  // Objects
  { emoji: '💡', description: 'light bulb', category: 'Objects', aliases: ['bulb'], tags: ['idea', 'light'] },
  { emoji: '💻', description: 'laptop computer', category: 'Objects', aliases: ['computer'], tags: ['pc', 'tech'] },
  { emoji: '🎨', description: 'artist palette', category: 'Activities', aliases: ['art'], tags: ['design', 'paint'] },
  { emoji: '🎵', description: 'musical note', category: 'Objects', aliases: ['musical_note'], tags: ['score'] },
  { emoji: '⚙️', description: 'gear', category: 'Objects', aliases: ['gear'], tags: ['settings'] },
  { emoji: '🔑', description: 'key', category: 'Objects', aliases: ['key'], tags: ['lock', 'password'] },
  { emoji: '🔒', description: 'locked', category: 'Objects', aliases: ['lock'], tags: ['security', 'private'] },
  { emoji: '🔔', description: 'bell', category: 'Objects', aliases: ['bell'], tags: ['notification'] },
  { emoji: '🚀', description: 'rocket', category: 'Travel & Places', aliases: ['rocket'], tags: ['launch', 'ship', 'staffmode'] },
  // Symbols
  { emoji: '✅', description: 'check mark button', category: 'Symbols', aliases: ['white_check_mark'], tags: [] },
  { emoji: '🎉', description: 'party popper', category: 'Activities', aliases: ['tada'], tags: ['party', 'celebration'] },
];